### ISSUE TITLE
Issues with "VocaDB player" on beta website

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1113]
I was testing the VocaDB player at the bottom on the beta website. I've been encountering some errors. It's not 100% reliable, but I'll try to provide information.

Browser: Microsoft Edge (Chromium) 100.0.1185.36
OS: Windows 10

1. Open song page such as [Next Nest](https://beta.vocadb.net/S/59428).
2. Click video, to start playing it.
3. Video starts playing, but sometimes without audio/video.
4. Sometimes this happens only after navigating to another song and attempting to play that. I can reproduce this almost 100% certainly after clicking a few songs/videos.

Errors that I saw in console:
* POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_FAILED from base.js:6290 
* Access to XMLHttpRequest at 'https://play.google.com/log?format=json&hasfast=true&authuser=0' from origin 'https://www.youtube-nocookie.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://play.google.com' that is not equal to the supplied origin.
* Failed to load resource: the server responded with a status of 500 () from /Song/PopupContentWithVote?id=160452:1 (sorry, I didn't get the content for this)
* Multiple 404s for resources, such as VocaDb.Model.Resources.json

**Comment by riipah** [comment]
![kuva](https://user-images.githubusercontent.com/550886/162621205-5fcc7e89-5caf-465e-adb2-425c6a9a9e8f.png)

**Comment by riipah** [comment]
It's possible the video playback problem is some browser optimization. Maybe it's not showing video if the player is hidden when starting playback. Anyway, you might want to investigate the errors.

**Comment by riipah** [comment]
Oh and the first error could be because of AdBlock too...

**Comment by ycanardeau** [comment]
I guess you cannot make use of them for this issue, but more detailed logs are available in the console. See https://github.com/VocaDB/vocadb/issues/804#issuecomment-1086624941.

> 3. Video starts playing, but sometimes without audio/video.

I'm aware of this issue, but I have experienced this only with Niconico and SoundCloud (the seek bar), but not with YouTube so far. And I've also experienced playing without video, but never without audio (Tested on Microsoft Edge Version 100.0.1185.29 (Official build) (64-bit) on Windows 11).

> Failed to load resource: the server responded with a status of 500 () from /Song/PopupContentWithVote?id=160452:1 (sorry, I didn't get the content for this)

Looks like it was a different server-side issue.

> Multiple 404s for resources, such as VocaDb.Model.Resources.json

This is not related to the new bottom player. Currently, the [`load` option of i18next](https://www.i18next.com/overview/configuration-options) is set to `all`, so it tries to load resources in the following order:

> Example: given set language is en-US: - 'all'  ⇒ ['en-US', 'en', 'dev']

However, since something like `locales/en-US/VocaDb.Model.Resources.json` doesn't exist, it throws a 404.
