### ISSUE TITLE
Suggestion: Button for "only edits" on user profile

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1141]
Opposite of "only additions". Especially for checking entries that had been edited by new user, this could be very useful. Basically preventing vandalism.

![grafik](https://user-images.githubusercontent.com/52045122/173825103-33cdfc14-08ed-47f7-bd93-77e1e5c0c2dd.png)

**Comment by ycanardeau** [comment]
How should the UI look like? I'm asking this because it's the most difficult (and time consuming) part of implementing something new. I'd say it's more difficult than coding, and we seriously need a UI/UX designer.

Examples:

Radio buttons:

![image](https://user-images.githubusercontent.com/51428094/173836221-dd84e6ef-5287-4180-af0d-b7e58d4e5c23.png)

Button group:

![image](https://user-images.githubusercontent.com/51428094/173836266-3bbd74d0-dd53-4f92-8c38-bf6a69e36a1e.png)

Buttons:

![image](https://user-images.githubusercontent.com/51428094/173836344-516f5854-b2a5-4a51-99a8-e53e4c0f459c.png)

Dropdown:

![image](https://user-images.githubusercontent.com/51428094/173836397-c7feb89f-205c-4cec-b955-227902963771.png)

Select:

![image](https://user-images.githubusercontent.com/51428094/173836444-a6e58bee-050e-4c3a-b675-cddde44b813a.png)

**Comment by andreoda** [comment]
I first thought that the radio buttons looked good but but they take some vertical space. The button groups are a good option.
