### ISSUE TITLE
Bug: invisible song lists on song entries

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1158]
Some song entries have song lists that are not possible to see when clicking on the text.

For example: https://vocadb.net/S/198721
It shows the number "2" but when you click on it, the pop up shows no lists.

I am not sure if this is related to the privacy setting to hide song and album ratings or if it is another bug (maybe it saves already deleted lists?).
In any case, it is probably better to **not** show the "Pools and song lists", if they are invisible to see.

**Comment by CatgirlFrostmoon** [comment]
Maybe it'd be good to list the amount of the song lists/pools attached to an entry, even if the link itself isn't available due to invisibility...? I'm suggesting this because some entries are kept from deletion due to having attached song lists, so it'd be good for us to be able to know that invisible lists exist.
