### ISSUE TITLE
API Ignores `accept: application/xml` Header

### ISSUE THREAD

**Issue by NetNerd** [VocaDB/vocadb#1174]
### Website
Tested on VocaDB, likely affects all if shared codebase

### Describe the bug
According to the wiki, the public API supports XML (https://github.com/VocaDB/vocadb/wiki/Public-API), but this seems to no longer be the case. The API always responds in JSON.
The accept header used to work fine, circa 2018~2019 or even later (see additional information below). Is it possible that some of the more recent changes (switching to ASP.NET Core?) could've affected it?

### To Reproduce
1. Send a request with `accept: application/xml` header (examples below).
    - `curl -G "https://vocadb.net/api/songs/1" -H "accept: application/xml"`
    - `curl -G "https://vocadb.net/api/artists?query=kz" -H "accept: application/xml"`
2. Observe that returned content is JSON.
    - `{"artistString":"","createDate":"2011-01-12T18:26:18", ...`
    - `{"items":[{"artistType":"Producer","createDate":"2011-10-10T02:24:27", ...`

### Expected behavior
API should respond in XML, or else documentation should be updated if this is no longer supported.

### Screenshots
N/A

### Desktop (please complete the following information):
N/A (tested on Windows 10 using .NET Framework's `System.Net.WebClient` and `curl`, but doesn't seem to be OS or application specific)

### Smartphone (please complete the following information):
N/A

### Additional context
I developed a MusicBee lyrics provider using the API several years ago, however I haven't really been keeping on top of maintenance since then. I recently received an issue report about failures, which prompted me to investigate (https://github.com/NetNerd/MB_VocaDbLyrics/issues/20).
The estimated 2018~2019 working date is just based upon when I last committed code (can be safely assumed to be working at that time). It could've broken soon after then or very recently, I don't know.

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [X] Tested on the **[beta site](https://beta.vocadb.net)**
- ~~[ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**~~
- ~~[ ] Checked in **private mode**~~
- ~~[ ] Cleared **browser cache** and **cookies**~~
- ~~[ ] Checked the **DevTools console**~~
- ~~[ ] Checked the **syslog** (mods+ only)~~

**Comment by ycanardeau** [comment]
> The accept header used to work fine, circa 2018~2019 or even later (see additional information below). Is it possible that some of the more recent changes (switching to ASP.NET Core?) could've affected it?

As you said, we [switched to ASP.NET Core in February, 2021](https://twitter.com/VocaDB/status/1363880316515983362) (See also #544), and it looks like [ASP.NET Core does not support XML serialization/deserialization by default](https://stackoverflow.com/questions/66383967/how-to-read-raw-xml-from-request-body-in-aspnet/66417953#66417953). According to this SO answer, it's super easy to enable XML serialization/deserialization, just by adding `AddXmlSerializerFormatters` to [`IServiceCollection`](https://github.com/VocaDB/vocadb/blob/7c699f64ec9763c931c500d313af31fb84425971/VocaDbWeb/Startup.cs#L57). I've tested it on my local machine, and it worked. However, I don't want to support XML if possible because there should be some performance penalty if I enable it, although I'm not sure how much it would be.

> API should respond in XML, or else documentation should be updated if this is no longer supported.

Thanks for your feedback! If I remember correctly, there was someone who also asked about this issue, so I'm wondering if `accept: application/xml` should be supported again. Anyway, I've enabled XML again for the [beta site](https://beta.vocadb.net) only for now. Your feedback is much appreciated.

**Comment by NetNerd** [comment]
Thanks for the quick response. I can confirm that the API works more-or-less the same as it used to (and definitely according to current documentation for the subset I use).
Ultimately it's up to you whether to enable it on the production site. I'd personally like to see it maintained, but if necessary I can revisit my old code and change it to use the JSON API. However, you should change this line on the wiki page if it will be JSON-only going forwards: `The API supports XML and JSON. The response format is determined by the HTTP "Accept" header.`

**Comment by ycanardeau** [comment]
Recently, we had to temporarily remove the `Swashbuckle.AspNetCore` and `Swashbuckle.AspNetCore.Newtonsoft` NuGet packages due to the [reported vulnerability](https://github.com/VocaDB/vocadb/pull/1184). In my opinion, enabling an opt-in feature increases the risk of this kind of vulnerability in the future as well, and the cost of maintenance. I decided to no longer support XML serialization/deserialization for the public API, and I've updated the wiki page. Thank you for your understanding.
