### ISSUE TITLE
Playlist autoplay no longer works

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1215]
### Website
VocaDB

### Describe the bug
Automatically playing liked songs on playlist mode no longer works. After the video ends, the next one doesn't automatically play even though the "autoplay" button is pressed.

### To Reproduce
1. Go to https://vocadb.net/Profile/Shiroizu/songs?viewMode=PlayList
2. Start any song, and click "autoplay"
3. Go to the end of the song
4. See error (next song doesn't play automatically)

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [x] Tested on the **[beta site](https://beta.vocadb.net)**
- ~~[ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**~~
- ~~[ ] Checked in **private mode**~~
- ~~[ ] Cleared **browser cache** and **cookies**~~
- ~~[ ] Checked the **DevTools console**~~
- ~~[ ] Checked the **syslog** (mods+ only)~~

**Comment by ycanardeau** [comment]
Currently, it's an expected behavior. I plan to remove the old playlist mode, replacing it with a new feature (to be announced). Please wait until it's implemented. Meanwhile, I can deploy the old playlist mode to the beta site (without the bottom bar), if you want.

P.S. I've added autoplay support for piapro and Vimeo.

**Comment by Shiroizu** [comment]
> Meanwhile, I can deploy the old playlist mode to the beta site (without the bottom bar), if you want.

That would be great, thank you!

**Comment by ycanardeau** [comment]
deployed
