### ISSUE TITLE
Tag search on event entries returns 404 (possible API typo)

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1281]
### Website
VocaDB

### Describe the bug
When adding tags to event entries, the input box keeps loading without returning any tag matches.

Console message shows "400 Bad Request" for the URL https://vocadb.net/api/tags?query=trance&target=ReleaseEvent
"The value 'ReleaseEvent' is not valid."

When changing the "ReleaseEvent" to "Event" in the URL, the API seems to respond properly.
https://vocadb.net/api/tags?query=trance&target=Event

### To Reproduce
1. Go to any event entry (https://vocadb.net/E/2041/comiket-100 for example)
2. Try adding any tag (by typing) that is valid for event entries (https://vocadb.net/T/52 "Cat" for example)
3. Observe a permanent loading circle

A current workaround is to enter the exact tag name, hit "Add" and "Save".

### Screenshots
![image](https://user-images.githubusercontent.com/15908050/205949257-39a0b4d1-2b6c-49fa-9715-5679a4273214.png)

### Desktop (please complete the following information):
 - OS: win10
 - Browser: Firefox107

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable.

- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
~~- [ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**.~~
~~- [ ] Checked in **private mode**.~~
~~- [ ] Cleared **browser cache** and **cookies**.~~
- [x] Checked the **DevTools console**.
~~- [ ] Checked the **syslog** (mods+ only).~~

**Comment by ycanardeau** [comment]
> When changing the "ReleaseEvent" to "Event" in the URL, the API seems to respond properly.

You're right. I haven't tested it yet, but defining a string enum `TagTargetType`, changing the type of [`tagTarget`](https://github.com/VocaDB/vocadb/blob/987cb3988d280efd5ab79222d381adfaf1cc2d0b/VocaDbWeb/Scripts/Components/KnockoutExtensions/TagAutoComplete.tsx#L16) from `any` to `TagTargetType`, and passing `TagTargetType.Event` instead of [`EntryType.ReleaseEvent`](https://github.com/VocaDB/vocadb/blob/f8de9163844b87ec4aaff365aaf1f76ff5e7a33b/VocaDbWeb/Scripts/Stores/ReleaseEvent/ReleaseEventDetailsStore.ts#L90) should fix this issue.
