### ISSUE TITLE
Suggestion: videos should never auto-play

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1285]
What I do often is, I play a video on VocaDB in one tab, then open other tabs for browsing songs. What VocaDB does, it starts playing the same song, from beginning, in all tabs. With NicoNico, it seems to be doing that even when I leave the site and come back. This is quite frustrating. I think the current model works well if you're using only a single tab, but not when using multiple tabs. I would suggest never auto-playing songs, or having an option to disable that. I would also be ok to (temporarily?) disable the persistent player at the bottom, when it's not needed.

Steps to reproduce:
1. Open any song page with video
2. Start playing the video
3. Open new tabs on VocaDB by middle-clicking (or right-click + open in new tab) any links on the song page

Expected outcome:
New tab opens with no video playing. Video keeps playing in original tab.

Actual outcome:
New tab opens with video playing from the beginning. All tabs are playing the same video individually.

Browser: Microsoft Edge 108

**Comment by riipah** [comment]
Another option would be to strictly constrain the video playback in one tab.

I'm not sure what the YouTube logic is. They have been changing it. I've never felt it intrusive, though, so whatever they're doing is probably fine.

**Comment by ycanardeau** [comment]
> What VocaDB does, it starts playing the same song, from beginning, in all tabs.

Yes, I'm [aware of this issue](https://github.com/VocaDB/vocadb/pull/1223#issuecomment-1252119157). The songs on the play queue are stored in local storage, and it will be restored when the page first loads. If there is any song on the play queue, the playback starts automatically.

Actually, I've already tried several approaches to fix this, but it didn't work well. I managed to prevent videos from automatically playing when opening in a new tab, but for example, YouTube's loading spinner keeps spinning until you start the playback, and I'm pretty sure you don't want to see this.

> Another option would be to strictly constrain the video playback in one tab.

Do you mean just like how SoundCloud does? If so, it would be definitely possible by using [`BroadcastChannel`](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel), and actually I was also thinking about this option.

> I would also be ok to (temporarily?) disable the persistent player at the bottom, when it's not needed.

Are you talking about 1.) disabling only the bottom-right mini player or 2.) disabling the entire player including the bottom bar?

> 2.

Adding an option to disable the entire bottom player would not be realistic, because I realized that it just increases cost of maintenance. As I said in VocaDB/community#171, this can be compared to the fact that the top and side bars can't be disabled. The bottom bar is now strongly integrated part of VocaDB, I'd say.

**Comment by ycanardeau** [comment]
> YouTube's loading spinner keeps spinning until you start the playback

I managed to fix this issue by replacing [`loadVideoById` with `cueVideoById`](https://github.com/VocaDB/nostalgic-diva/commit/5daa04b2e3766a64ffacfb48c783c0cc35e97f9d).

**Comment by riipah** [comment]
It's fine now, thanks for fixing it. 

One shouldn't underestimate the importance of "little" usability things like this. It can make all the difference in how pleasant it is to use the website. Originally when I was thinking about it, I was planning to make the persistent video player mode separate option, because it's a separate use case. One use case is finding specific information about songs and artists, another is checking new songs, third is browsing songs similar to how you'd use YouTube. That's always the issue with adding new features: if you're not careful, that new feature may make previous experience worse. For this reason, I would still say that having an option to disable the bottom player would make sense, because it's only needed for the third use case ("YouTube mode"), and takes valuable screen space from other use cases. It should also be very, very simple to have a condition to show or not show the player/bar, so there shouldn't be much maintenance overhead. But, I'm satisfied with the current solution.
