### ISSUE TITLE
Add lang= attribute to html tag

### ISSUE THREAD

**Issue by quex6422** [VocaDB/vocadb#133]
For example, [Korean Wikipedia](https://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8C%80%EB%AC%B8) uses `<html lang="ko" dir="ltr" class="client-nojs">`.

See also [Why use the language attribute?](https://www.w3.org/International/questions/qa-lang-why.en)

**Comment by riipah** [comment]
I'll think about it. It's not that easy on VocaDB because our pages are dynamically generated, unlike wikipedia. Additionally, since we have the UI language and content language separate, I don't think it's as useful for us.

**Comment by riipah** [comment]
Ok, I added it. I'm still wondering about mixed languages though. HTML5 allows defining language per element, but this would be a lot of work, and we still can't always identify the specific language of the content (non-English could be Japanese, Chinese or something else). One lang attribute for the html tag should be ok though since that's just the main language of the page
