### ISSUE TITLE
Song entry: New field for language

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1408]
### Is your feature request related to a problem? Please describe.
A song's language can be determined by the (original) lyrics added to the song entry but many entries do not have lyrics added to them (Either because they are not added yet or they couldn't be found).
Another way of setting a song's language is by adding language tags but that should be avoided in a better system.

### Describe the solution you'd like.
There could be a field in the song entry where users could set a song's (main) language.
It could be displayed under or above the "Duration" field and could have the same drop-down menu as given in the lyrics options.

----

Related issues:
- https://github.com/VocaDB/vocadb/issues/1383
- https://github.com/VocaDB/vocadb/issues/1409

**Comment by FinnRG** [comment]
I think this is a good idea. Here are some stats:

- English: 5100 songs with English lyrics / 12500 songs tagged with "English" 
- Spanish: 300 songs with any lyrics / 1100 songs tagged with "Spanish"
- French: 100 songs with any lyrics / 350 songs tagged with "French"

Thus, deriving the language of a song from the original text only gives us about 1/3 of all songs, so a newlanguage field should provide valuable additional data.

But there are still some open questions. 

1. What if the user selects a different language for the original text and the new language field? Should we just give a warning or reject the entry? Should the language field be disabled if there are original lyrics?
2. Should we infer the language for certain voicebanks?
3. Should we automatically add the language for some derived songs? And if so, what types of derived songs imply unmodified language?

**Comment by andreoda** [comment]
1. What if the user selects a different language for the original lyrics and the new language field? Should we just give a warning or reject the entry? Should the language field be disabled if there are original lyrics?

A: I think the lyrics language should be automatically added into the language field if they are available. Same should be done vice versa: When entering the lyrics tab, the original language will already be chosen and can not be changed (greyed out), only the lyrics can be added/edited.
I mean, the lyrics and the language field should be somehow connected.

2. Should we infer the language for certain voicebanks?

A: Maybe there could be suggestions displayed or nothing at all. I am not sure what is the best option here.

3. Should we automatically add the language for some derived songs? And if so, what types of derived songs imply unmodified language?

A: Note that lyrics (in the lyrics tab) are already inherited from the original entry automatically. If both, the language and the lyrics are connected, it would make sense to follow that pattern.

Some cover songs etc. can have changed language. Perhaps it could be connected to the tag "changed language" in a way that the lyrics/languages are not copied.

**Comment by Shiroizu** [comment]
Agreeing with @andreoda's points.

> 1. What if the user selects a different language for the original lyrics and the new language field? Should we just give a warning or reject the entry? Should the language field be disabled if there are original lyrics?

Having a warning seems like the safest choice. There can be some edge cases where it doesn't make sense to disable the field.

There are a few languages that currently can not be added as "lyrics":

- [gibberish/nonsensical lyric](https://vocadb.net/T/1739) (currently not an available option for lyrics)
- [fictional language](https://vocadb.net/T/1731/fictional-language)

I think it'd make sense to add these instead of reverting to "other/unknown".

How to handle bi/tri-lingual songs (where the language share is equal) is one open question.

> 2. Should we infer the language for certain voicebanks?

Safe for maybe 99% of the songs. Although 1% is around ~4 000 entries which is a bit too much.

**Comment by andreoda** [comment]
One more addition:
These are the lyrics tags we currently have (for reference):
![grafik](https://github.com/VocaDB/vocadb/assets/52045122/149de1dc-15bc-4531-a6ba-5db7685c76de)

**Comment by CatgirlFrostmoon** [comment]
Are we going to be making it so that we can set the language of artist entries, too? Or would we continue to use tags for them?
And yeah, I'd like to second Shiroizu's note about how we handle multilingual entries; a song like "Dancer in the Dark" utilizes both English and Japanese in relatively equal measure, so trying to label it as only "Japanese" or only "English" is something of a misnomer.
