### ISSUE TITLE
A specific user profile does not load

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1478]
### Website
VocaDB

### Describe the bug
https://vocadb.net/Profile/Flower%20Metal is active account +trusted user, but does not load:

- has header
- has the buttons under the header
- does not have anything else

The API response doesn't immediately look malformed; it has # of edits, rated songs, etc.

### To Reproduce
click on the link (I encountered it at https://vocadb.net/Album/Versions/1135 FWIW)

### Expected behavior
a normal user profile

### Screenshots
from Andreoda:
https://cdn.discordapp.com/attachments/797103264655081492/1113093423898050670/image.png

### Desktop (please complete the following information):
n/a

### Smartphone (please complete the following information):
n/a

### Additional context
n/a

### Checklist

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [ ] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Checked in **Chrome**.
- [ ] Checked in **Safari**.
- [ ] Checked in **Edge**.
- [ ] Checked in **Firefox**.
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
This issue has multiple layers:
1. The user has a space in their name, which we normally don't allow. It would be interesting to know how they changed their name
2. This wouldn't normally be a problem, but the exact version of react router (our internal routing library) we are using has a bug, that causes it to not handle spaces correctly (https://github.com/remix-run/react-router/issues/9580)

So the bug can be fixed with a simple library update, but I should probably activate dependabot to prevent future issues with outdated libraries.
