### ISSUE TITLE
[Bug report] Unable to add SoundCloud media

### ISSUE THREAD

**Issue by jaj-a11y** [VocaDB/vocadb#1820]
### Website (required)
VocaDB 

### Describe the bug (required)
When trying to add a SoundCloud URL to "Media" on a page, after a few seconds of waiting, an error pops up and it doesn't work. This doesn't happen everytime and I can't determine a common factor between the links that didn't work.

### Screenshots (optional)
![firefox_2024-10-21_19-33-06](https://github.com/user-attachments/assets/d0503518-c58b-42c4-a904-b77ba1e07f14)
https://vocadb.net/S/688855

### Desktop (optional)
 - OS: Windows 10
 - Browser: Mozilla Firefox (tested on Chrome, behaves the same)

### Additional context (optional)
*A confusing factor: when this first happened yesterday, I happened to have accidentally pasted the wrong URL anyway. When I tried again with the right URL, it worked. Then, I edited the page on which I actually intended to add that "wrong URL". It worked, which implies the issue didn't lie with that URL/track itself *nor* did it lie with that first entry.
*Another user reported the same issue in entry-report-notifs on Discord

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, ~~**Safari**~~, ~~**Edge**~~).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and ~~**cookies**~~.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by saturclay** [comment]
This happens to me too, but usually just trying again immediately fixes it (at least in my experience).

**Comment by FinnRG** [comment]
The issue seems to stem from a timeout with my custom yt-dlp proxy, which was necessary while the SoundCloud API was not open to the public. The proxy machine goes to sleep after 10 minutes of inactivity, causing the first request to take longer as it needs to wake up the service. This often exceeds the 10-second timeout set on the server, resulting in a failure.

To fix this, I've made some adjustments: the machine will no longer go to sleep, and I've increased the timeout to 20 seconds.

These changes will be applied with the next update.
