### ISSUE TITLE
[Bug report] Language Display - Submit a song

### ISSUE THREAD

**Issue by FireWall0123** [VocaDB/vocadb#1821]
### Website (required)
VocaDB 

### Describe the bug (required)
When creating a new song entry and setting the song type to "Cover", the description box bottom-right always switches to Japanese regardless of the chosen display language.

### To Reproduce (optional)
1. Go to '[Submit a song](https://vocadb.net/Song/Create)'
2. Click on 'song type' and change it to 'Cover'

### Screenshots (optional)
https://github.com/user-attachments/assets/2ad74bf7-9ab1-4ea3-aee6-c351a887ad07

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
This is tied to the "Preferred display language" setting in the interface section of the [user settings page](https://vocadb.net/User/MySettings). You only see this effect with the cover tag, because it's the only translated song type tag.

@Shiroizu @andreoda Should the tag description box use the "interface language" (UI elements) or the "display language" (entry titles, tag descriptions) setting?

**Comment by Shiroizu** [comment]
@FinnRG - I think this kind of split is the most intuitive:

- **Interface language** = UI language, translations through crowdin: https://crowdin.com/project/vocadb
- **Display language** = Entry language, translations through entry edits

The line of UI/entry is blurred a little here, since the tag entry description is displayed as a part of the UI. 

Based on the above distinction, I think in this case the behaviour is intended.

Ideally the edit instructions would be sourced from the wiki instead: https://github.com/VocaDB/vocadb/issues/134#issuecomment-2246445869
