### ISSUE TITLE
Peculiar sorting order in tag clouds

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#185]
At http://vocadb.net/Tag I see tags sorted as, e.g:

...robot   romance   RPG   sadism   cherry blossom   Santa Claus  Santa Miku  satellite...

The "cherry blossom" tag is "sakura", and it gets sorted near other "sa..." -- even though that's not the actual name displayed. IMO sorting in this case should take into account which name is displayed, and this tag should be sorted to belong among the other "ch....." ones.

**Comment by riipah** [comment]
It should be noted this only happens when content language preference is "Original". For all other settings it should work as expected. Currently it's not possible to sort by "original" name - it uses the non-English sort. This applies to all entries, but it's generally not as apparent for other entries besides tags, because for those the original language is usually the same as non-English selection. In order to change this for tags, it would have to be changed for all entry types with translations.

I agree it would be better to add proper sorting for "original" content language, but it's a large change for relatively small improvement, so probably I won't have time to do it any time soon.

**Comment by riipah** [comment]
I managed to do it without database changes by selecting the sort column dynamically. There's some small performance penalty, but it shouldn't be too much
