### ISSUE TITLE
More fields for /api/entries

### ISSUE THREAD

**Issue by jsmnbom** [VocaDB/vocadb#187]
Hello Riipah,
Would it be possible to have some of the fields from /api/songs and /api/artists in /api/entries?
I realise it wouldn't be possible to get all fields back on all requests fx. if I request 'PVs' and it's an artist, but in such case it could just be empty or non-existent.
If it's too difficult or something like that, I understand :)
-bomjacob

**Comment by riipah** [comment]
I guess it's possible, but what do you need it for?

**Comment by bomjacob** [comment]
I'm currently writing v2 of my VocaBot (VocaDB Telegram Bot).
I want to get the bot working in inline mode (see below gif) which means that when you type @BOT_USERNAME in any chat it will pop up a small window where you can search. 
This means that to display that window I need basic details about the song/artist and also mainpicture. Because I couldn't get /api/entries to work properly when I was coding v1 I made it such that it searches both /api/artists and /api/songs, it only displays a single artist though (since I'd have no way to sort them). I would like to use /api/entries now though as it's not very user-friendly only showing a single artist (fx. when searching "Masa" "Clean Tears" shows up instead of the intended "Masa") - if it showed multiple artists the user could choose the correct one themselves.
I thought that it would be no problem to convert to /api/entries, but the problem I'm running into that that because of the telegram API, when I send the results that pop up in that window, I also need to send the message that would get send if the user presses one of the results incl. the buttons. One of the buttons I show is based on "pvServices" of /api/songs, but I'm unable to get that field with /api/entries.
![](https://i.imgur.com/JBJnYic.gif)
I really hope that made sense, it's a bit hard to properly formulate in text - if you got any question/couldn't understand what I wrote, just say so :)

**Comment by riipah** [comment]
Is PVs the only thing you need?

**Comment by bomjacob** [comment]
Yeah, I think so actually. Lyrics would be a waste of data to request (especially since it's behind a button press anyways) and same with Artists.

**Comment by riipah** [comment]
Ok, [I added PVs](http://vocadb.net/api/entries?query=&fields=PVs).

**Comment by bomjacob** [comment]
Thanks a lot 👍

**Comment by bomjacob** [comment]
Actually, I'm really sorry for realising this so late.
But would it be possible to also have favoritedTimes and perhaps ratingScore too?
It would be awesome to also have followerCount for artist.

**Comment by riipah** [comment]
I'm a bit reluctant to add too many of the entry type -specific fields in entries API, to avoid making it too complicated.

Follower count is not saved in the DB, it's an aggregate value displayed on artist details page.

**Comment by bomjacob** [comment]
Ah, yeah that makes sense actually. Just thought it would make sense to pass it along, since stuff like `song_type` is already present. But I'll just have it not show favoritedTimes when searching for anything then, that works :)
Oh okay, don't know how I'd gotten into my head that it was a field :/

**Comment by bomjacob** [comment]
I'm just gonna ask this here, since I don't know where else I can.
Say I wanted to credit you in the bot's about page. Do you have a telegram account? (@riipah maybe)? or should I make it a link to your twitter. Or should I simply not credit you as the "author" of VocaDB?

**Comment by riipah** [comment]
I don't have a telegram account. You should primarily credit [VocaDB](https://twitter.com/vocadb) for any  information you're getting because I'm not the only one editing.
