### ISSUE TITLE
Saved search configuration presets

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#2]
User should be able to store a search configuration as a named preset. For example, all songs with the tag "vocarock" where the artist is "Kagamine Rin" and her child voicebanks. Song search presets would also function as dynamic song lists.

In addition to personal search configuration presets, there could be shared presets, in the same way as featured song lists. Only moderators are able to maintain these shared presets (the featured song list management role can probably be re-used).

**Comment by dset0x** [comment]
This certainly sounds nice.  In fact, if powerful enough it could sort of replace user's mailboxes. All your follows could be such a dynamic list (although follows include more than songs; e.g. albums).

This makes me think about another feature: Encoding all searches into the URL, so that searches can be shared with others.

I wonder which of the two better helps us, if not both.

**Comment by ycanardeau** [comment]
> Encoding all searches into the URL, so that searches can be shared with others as links.

@dset0x This could be done by #163 (maybe along with "React conversion").

**Comment by dset0x** [comment]
> > Encoding all searches into the URL, so that searches can be shared with others as links.
> 
> @dset0x This could be done by #163 (maybe along with "React conversion").

Thanks for pointing that one out!

**Comment by ycanardeau** [comment]
@dset0x The future is now, old man!
