### ISSUE TITLE
Playlist player tries to play songs with unavailable media

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#310]
If a song is tagged with "original media unavailable" and only has URLs to original media, playback will fail. I would argue these are equivalent to having no media at all as far as the player is concerned.

This is a nice-to-have so perhaps it can go down the priority list, especially if there's much concern over allowing a tag to affect the UI.

**Comment by riipah** [comment]
Auto-play doesn't even support NicoNico, because NND doesn't have JavaScript controls. So this is only a problem for non-autoplay, in which case you can easily skip songs that won't play (we could even automate that for YouTube). Implementing the filtering based on tag and the list of PVs is a bit complicated, and it's not even completely reliable because those tags are managed manually, so I don't think it's worth it.

**Comment by disqonnected** [comment]
Indeed, I am not referring to NND videos on non-autoplay (which I never use myself). Either way, understood, thanks.
