### ISSUE TITLE
"Mark as read" button for reports

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#315]
Currently there is an exclamation mark in the "Account" button and a report count in the "Entry reports" menu item as long as there's non-zero amount of open reports globally.

However what if these are all reports that a user can't or doesn't want to act on. In this case it would be nice to click a button such as "Mark all as read" and have the notification go away, until more reports arrive and need to be checked out.

As currently the ever-present exclamation mark doesn't play its role in notifying to re-check the reports section, as you never know if there is something new, or it's just the old ones you've already seen.

**Comment by romanrm** [comment]
A more drastic approach would be to implement this "mark as read" behavior without an explicit button, as soon as a particular list of reports is shown to a user (same as with unread/read private messages).

**Comment by riipah** [comment]
Not important enough considering the significant amount of work

**Comment by Nefere256** [comment]
I made a similar feature few months ago in another project (notifications for multiple users) where the read option was already present. The read action there is made by click, but the backend part may be implemented in similar way.

The feature involves adding a collection of helper objects linked to an entry report and containing a receiver's `username/userGroup` and `isRead` boolean. New entry report would be created initially with the helper object with ex. `"trusted+" as receiver's userGroup` and `isRead=false`, and the collection would be populated with every user reading entry reports list with `isRead=true`.

Preparing a list/count of reports to read would be more tricky - it's needed to search for objects with specific `username` or `groups` assigned to the user. Objects with matching `username` take precedence. If nothing can be found for the specific entry report and user, it's assumed the entry report is not for them to see.

The collection can be cleared from info who read the entry report when it's closed.

----

If it would be implemented this way, we can make use of "set a group as a receiver" feature and hide some of the reports from trusted users - they can do nothing about spammer notifications or artist ownership requests.

**Comment by riipah** [comment]
> If it would be implemented this way, we can make use of "set a group as a receiver" feature and hide some of the reports from trusted users - they can do nothing about spammer notifications or artist ownership requests.

I want everyone to see the spammer notifications. Even if they can't disable, they can still keep an eye on the potential spammers.

**Comment by riipah** [comment]
Main problem with this issue is that entry reports are global (not user-specific), and that's how they should be, because only one user can handle them. Meanwhile those read notifications would need to be per user. So that requires a new related entity ("linked object" as you said) to be created. Nowhere near impossible of course, but still a significant amount of work. 

There is also the point of view that reports are intended to be short lived. Ideally only 1-2 days max. If the report cannot be resolved, then I usually recommend creating a comment and closing the report. Therefore such read acknowledgements would be short lived as well. Of course sometimes reports stay there a bit longer when they require a response from someone, but from what I've seen, most reports should be closed much faster than they currently are.
