### ISSUE TITLE
Can we have more than one set-list related to an event ?

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#340]
After the problem with the miku with you setlist
http://vocadb.net/E/1619/miku-with-you

even for http://vocadb.net/E/1397/magical-mirai-2017

there could be 3 setlists, it would be better for everyone (IMO)

we can just have  a number (and a custom name as well) for the running order (afternoon concert, evening concert) or by days

**Comment by riipah** [comment]
Are you sure it's going to be simpler that way? Having multiple setlists... You can already indicate changed songs with comments.

**Comment by Move-Forward39** [comment]
What about one setlist, but being able to specify when a song is in the same position as the one above it? The result may be something like this (this is just a mock-up I did in Paint to give a visual): https://imgur.com/7uHkbrL

The specifications could be done with a checkbox like this (again, just a mock-up quickly done in Paint): https://imgur.com/xuLlVJY
(May be a good idea to exclude the first song from this option.)

This way, we can still have one setlist per event (assuming no event is going to have drastically differing setlists) and changes are specified and laid out. I don't know how hard this would be to implement, though.

**Comment by riipah** [comment]
Yeah, that would work as long as the order of songs hasn't changed, which I assume they haven't done yet, but might very well do in the future. Also, showing them side by side doesn't really work because at MM they had 3 songs in the same position, and it would take too much space even for desktop (only HD screens could show even those 2 side by side). That said, it could still be possible to group them visually somehow even when displaying vertically, and also give them the same number, if you think that's enough. But again, that won't work if they suddenly start moving songs around instead of just adding/removing songs.

**Comment by Move-Forward39** [comment]
Perhaps we can have the songs match in number and have the same background color (the soft, transparent blue or the beige). That might be enough visual for vertical display (+ comments, of course).
For viewing an event and seeing its setlist (like here, for instance http://vocadb.net/E/1619/miku-with-you ), there are no backgrounds used, so I'm not sure about in that case other than the number change (and, would it be possible to have comments on songs on the setlist show on the event entry as well? That may help, too).
After another Miku Expo with many venues would help determine that, like that tour they had in North America. I don't know when that'd be, though...

**Comment by riipah** [comment]
Perhaps I will add the checkbox. It should take care of most cases. And then display the songs on different rows, but with the same number. The checkbox should only be shown if song list type is "concert setlist".
