### ISSUE TITLE
Double asterisk not making text bold

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#448]
I have double asterisks around "Birthdate:" here, but for some reason, it shows up as "*Birthdate:*" in italics instead of bold, but all other instances of double asterisks work just fine.
I'm not sure what the issue is. If it's user-end, I'm not sure how to fix it.

**Comment by riipah** [comment]
Where is "here"?

**Comment by Move-Forward39** [comment]
Sorry for the late reply. Must have forgotten the link: https://vocadb.net/Ar/62632

**Comment by Move-Forward39** [comment]
And I hit "Comment and close" instead on just "Close". Let me reopen it.

**Comment by riipah** [comment]
The problem is that Markdown (the markup syntax used by VocaDB and many other sites) isn't exactly standardized, so there is no way to predict how exactly it will render. VocaDB uses a library called [MarkdownSharp](https://github.com/StackExchange/MarkdownSharp). I think the library was confused by the title, which had nothing after the asterisks. I added an empty line after the title, and now it renders fine. Sometimes it takes a few attempts. Nothing we can do about it, that's how Markdown is.

**Comment by Move-Forward39** [comment]
Ah, okay. Thank you!
