### ISSUE TITLE
Verifying again after closure

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#487]
Someone was trying to request for verification of their account after they had done it before. The previous one was closed because it didn't have everything necessary.
The entry report didn't show up, though. Is there something that prevents an artist from trying to verify/claim a page a second time? (That is, the same artist page a second time, after the first one was closed and they weren't verified)

**Comment by riipah** [comment]
There is a check that prevents submitting an entry report by the same user for the same entry. It's by design, although it hasn't been updated to take into account the report status (if it's closed, maybe another report could be allowed). The intention is to prevent user from spamming the report function indefinitely, because it can also be used without logging in. I guess we could allow duplicate reports in some situations, for logged in users or if the previous report is closed.

**Comment by riipah** [comment]
You wouldn't believe how many new test cases this needs
