### ISSUE TITLE
Manage JavaScript dependencies with webpack (or similar)

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#5]
## Current status
Currently we're using [ASP.NET bundling and minification library](http://www.asp.net/mvc/overview/performance/bundling-and-minification). There's separate [bundles](https://github.com/riipah/vocadb/blob/master/VocaDbWeb/App_Start/BundleConfig.cs) for all main views, in addition to a couple of shared bundles. As the number of JavaScript files grows, managing dependencies is increasingly becoming a problem. We don't want to include all JavaScript files on all pages, and the files need to be included in the right order, so managing the bundles becomes complicated. 

## Goal

Nowadays [TypeScript](https://www.typescriptlang.org/docs/handbook/modules.html) and EcmaScript (JavaScript) include built-in support for modules. Dependencies can be defined by importing modules.

When all dependencies are defined with import/export, a module bundling tool like Webpack can be used to create the bundles.

Of course this would be nearly impossible to do at once, so if we are to consider using Webpack, it has to be done somehow incrementally per file. Knockout includes some support for dynamically loading modules, but since VocaDB isn't a SPA (except for maybe the search page), it would be ok to include bundles per ASP.NET page. 

Ideally we'd have one big bundle for common dependencies, plus page-specific bundles for page's viewmodels, similar to current ASP.NET bundles. For example, "bundles/main", which includes files used on most pages, "bundles/song/edit", which includes files on song/edit page (SongEditViewModel.ts + /song/edit.ts + their dependencies).

**Comment by ycanardeau** [comment]
I'm trying to solve this issue by using ES2015 modules and Laravel Mix. Please see 61c353a7d125c53f02f1716aa48bf7ae7f403042.

**Comment by riipah** [comment]
Hmm, I'm not familiar with laravel. I see you also have webpack there?

The end goal would be to use TypeScript/ES6 modules to manage dependencies between files, with import/export. Things have improved a lot since 2015, most of the module handling is now build-in.

Do you think it would be possible to convert pages/files one by one to use import for dependency management?

**Comment by ycanardeau** [comment]
[Laravel Mix](https://laravel-mix.com/) is a wrapper around Webpack.

I converted pages/files at once, not one by one.

Instead of having page-specific bundles for page's view models, I included all page-specific modules in [App.ts](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Scripts/App.ts), which is about 200 KB when it is bundled in production mode.

**Comment by riipah** [comment]
Thanks. I'll try to review later this week.

Do you think eventually it would be possible to add import clauses to individual TypeScript files and then for example say "I want a bundle that includes these two files and all their dependencies"?

So for example

```typescript
import './KnockoutExtensions/FormatDateFilter';
import './KnockoutExtensions/FormatLengthSecondsFilter';
import './KnockoutExtensions/BindingHandlers/DatePicker';
import './KnockoutExtensions/BindingHandlers/ReleaseEventAutoComplete';
export { default as SongEditViewModel } from './ViewModels/Song/SongEditViewModel';
export { initPage as initSongEditPage } from './Song/Edit';
```

Those imports would be in SongEditViewModel.ts and Edit.ts.

**Comment by ycanardeau** [comment]
Do you mean that you want a page-specific bundle (e.g. `~/bundles/Song/Edit.js`, which includes [SongEditViewModel.ts](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Scripts/ViewModels/Song/SongEditViewModel.ts), [Edit.ts](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Scripts/Song/Edit.ts) and their dependencies) instead of having one big bundle (`~/bundles/App.js`, which includes all dependencies except for third-party libraries ([jQuery](https://jquery.com/), [jQuery UI](https://jqueryui.com/), [Knockout](https://knockoutjs.com/) and etc.) used by VocaDb)? If so, I think it would be possible, but I don't know the right way to do that.

**Comment by riipah** [comment]
Yes, that is exactly what I think we should have. Or at least, if we make changes to the bundling, there should be a clear path to that goal, IMO. 

That's how it's done for all new projects I've been working with. I mean, isn't that the point of Webpack? To make bundles that include one file/class and all its dependencies. If you want all JavaScript files you could just bundle them all with gulp.

**Comment by riipah** [comment]
So do I understand correctly that on the server there is one big bundle file (app.js) which includes all those bundles, but the client is loading the bundles one by one. For example, song edit page is still loading just the bundles/song/edit bundle? If so, then that works for now too. But I would still like to keep in mind the end goal where dependencies are specified in the file itself with import commands, instead of listing them all in one big app.ts.

**Comment by ycanardeau** [comment]
> on the server there is one big bundle file (app.js) which includes all those bundles

Yes.

> but the client is loading the bundles one by one

No (although I'm not sure I understand this question properly, probably [AMD](https://en.wikipedia.org/wiki/Asynchronous_module_definition)?), the client is also loading the big bundle file `~/bundles/App.js`. Laravel Mix compiles all assets (Knockout extensions, models, repositories, view models and etc.) into `~/bundles/App.js`. However, I think it is not so problematic for now because the `~/bundles/App.js` is as big as `./bundles/libs.js`, which includes third-party libraries.

> dependencies are specified in the file itself with import commands, instead of listing them all in one big app.ts.

The modules used by **TypeScript files** (e.g. [SongEditViewModel.ts](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Scripts/ViewModels/Song/SongEditViewModel.ts#L5)) can be specified in the file itself with import commands. The modules used by **views** (e.g. [Edit.cshtml](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Views/Song/Edit.cshtml#L376)) must be listed in [App.ts](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Scripts/App.ts#L162).

**Comment by riipah** [comment]
Oh, I thought that LaravelMixHelper class is doing that, loading individual bundles from the app.js file. What is it for then?

As far as I understand, AMD is for situations when you're writing a real SPA (single page application), which loads additional dynamically files as you navigate. For example, if search page and song details page were both rendered with JavaScript, they could be on the same .cshtml page, no need to load another page from the server. This is what you can do with modern SPA frameworks. Knockout has limited support for that, but VocaDB is pre-SPA. Most of the pages are on different .cshtml pages, so if you want to navigate from search page to details page, it loads a new .cshtml/HTML page from the server. The upside is that there is no need to load JavaScript bundles dynamically: it can be included on the .cshtml page.

Currently we have 3 types of bundles: library bundles (bundles/libs), shared bundles (like bundles/main) and page-specific bundles (like bundles/song/edit). I guess it would be ok to get rid of the page-specific bundles and move all of application code to the shared bundles, if it doesn't slow down the initial page load too much.

**Comment by ycanardeau** [comment]
[Laravel Mix](https://laravel-mix.com/) emits `mix-manifest.json` when [versioning](https://laravel.com/docs/5.8/mix#versioning-and-cache-busting) is enabled. [LaravelMixHelper](https://github.com/VocaDB/vocadb/blob/59443fbb53d9b97d6eed82054065b76aa20197f1/VocaDbWeb/Helpers/LaravelMixHelper.cs) class reads this file and generates a `link` or `script` tag containing the path to a versioned file.

References:
https://laravel.com/docs/5.8/helpers#method-mix
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Mix.php

**Comment by ycanardeau** [comment]
I've been updating [ycanardeau:future](https://github.com/ycanardeau/vocadb/tree/future) by merging from [VocaDb:master](https://github.com/VocaDB/vocadb/tree/master), but the difference between [VocaDb:future](https://github.com/VocaDB/vocadb/tree/future) and [ycanardeau:future](https://github.com/ycanardeau/vocadb/tree/future) is getting bigger and bigger. There are already 118 changed files with 967 additions and 476 deletions as of now. If I apply this change to event venues too, then the difference gets even bigger. I wonder when I should create a pull request to [VocaDb:future](https://github.com/VocaDB/vocadb/tree/future). Has the spam problem (you mentioned in #553) been solved? Should I refrain from creating new pull requests for a while?

**Comment by riipah** [comment]
It's not so much about the spam problem, although that still needs some improvement too (#564 mainly).

It's just that getting this to production needs changes to deployment, and also some testing to make sure everything still works. I cannot do that now. In general I have very limited time to work on this project. I'm hoping that during summer holidays it might be better. So expect that it might take 1-2 months or even longer until I can get future merged to master, but it is my intention to do it eventually.

It would be better to get merge new things to master instead of future, so that we can get them to production faster, instead of all at once. If you're worried about future branch drifting from master, better focus on backend-related tasks such as the email validation.

**Comment by ycanardeau** [comment]
> It would be better to get merge new things to master instead of future, so that we can get them to production faster, instead of all at once. If you're worried about future branch drifting from master, better focus on backend-related tasks such as the email validation.

Oh, I am worried about the amount of code you have to review when [ycanardeau:future](https://github.com/ycanardeau/vocadb/tree/future) gets merged into [VocaDb:future](https://github.com/VocaDB/vocadb/tree/future) (not [VocaDb:master](https://github.com/VocaDB/vocadb/tree/master), I'm updating [ycanardeau:future](https://github.com/ycanardeau/vocadb/tree/future) so that [VocaDb:future](https://github.com/VocaDB/vocadb/tree/future) can be merged into master without conflicts) rather than about future branch deviating from master. It looks like you have limited time on this project, so I wondered if I should refrain from creating new pull requests.

**Comment by riipah** [comment]
It took a while, but I set up the "beta" website at https://beta.vocadb.net/. That is now using the "future" branch and has the laravel mix bundles. It actually worked fine, I just needed to add npm install to my build script. Let's keep it there for a while, let someone test it and if it works fine then I can merge it to master.

**Comment by ycanardeau** [comment]
Thank you so much for your work!
