### ISSUE TITLE
Lyrics/ID for the original version on covers/remixes in the API

### ISSUE THREAD

**Issue by NetNerd** [VocaDB/vocadb#55]
The current API doesn't offer a way to retrieve lyrics for covers and remixes which on the website pull the data from the original version of the song.
Either the API behaviour should match the site behaviour for returning lyrics, or a way to determine the original song's ID should be added.

**Comment by netnerd** [comment]
I'm not familiar with the codebase for the site, but I've gone ahead and forked the repo so I can experiment.
I think that my commits at https://github.com/netnerd/vocadb/commits/master should solve the issue (at least partially), but I don't really have the time to set up a dev environment and test it.
I'm also not sure about the capitalisation of the '.id' after 'song.OriginalVersion'. It looks to me like it should be lowercase from some searching, but I know that there's some cases of '.Id' too, so idk. It's not a complex fix at all by the looks of it.

**Comment by riipah** [comment]
It has to be "Id" with an upper case "I" because that's how properties are named in C#. The JSON serializer will convert it to camelCase, meaning lower case "id". You'd also need to check for null because now it will crash if OriginalVersion is null. Maybe name the property to OriginalVersionId, and since it's just the ID, there's not really need to make it optional (your can remove it from SongOptionalFields and always include it).

**Comment by netnerd** [comment]
Cool. I guess I can do that.
You can probably tell I don't code for a living though with those mistakes.

**Comment by riipah** [comment]
Neverthelews, better than anyone else has done so far

**Comment by netnerd** [comment]
Well, I guess so... *checks contributors*
You're not kidding, are you? Seems like you're the only one who's contributed any significant code!

**Comment by riipah** [comment]
@netnerd: when you're done, please create a pull request so I can review it

**Comment by netnerd** [comment]
Oops. I think it should be okay for now how it is, so I guess I'll go do that.
I'm guessing it's probably best to not bother about the lyrics from the original version like I originally mentioned. That would just unnecessarily complicate things.

**Comment by riipah** [comment]
That can be done too, but it'd be a separate option, not the default I think

**Comment by netnerd** [comment]
I guess, but it's not really hard for that to be user handled and doesn't really relate to the current song that much. 
Anyway, I guess I'll polish up the library I wrote for getting lyrics and release that sometime now (yay -  shitty VB.NET code XD). All my previous  programming is for personal use because I don't really like people judging my poor and ugly code :P. But lol, I think this might be the first thing I wrote that I actually think is decent. 
Anyway, this is irrelevant. If you think the code's good, feel free to close the issue.

**Comment by riipah** [comment]
It needs some fixing (as shown by the failing unit tests), but it's ok, I can finish it

**Comment by netnerd** [comment]
Fair enough. It probably would've been easier to just let you do it in the first place. 
Thanks for putting up with me and getting this in the API.
I guess you can get rid of that new pull request too then, if it fails tests.

**Comment by riipah** [comment]
I did it a bit differently anyway, there's a method called HasOriginalVersion that you're supposed to use, it also checks that the song type isn't "original".

**Comment by netnerd** [comment]
Aah. That sounds logical.
/me sucks :)
