### ISSUE TITLE
Use ElasticSearch for the search page

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#665]
Split from #663

**Comment by riipah** [comment]
Allow me to elaborate that ElasticSearch, based on Lucene text analysis, is a text search engine, somewhat similar to Google, but more customizable. Self-hosted ElasticSearch is free under Apache 2.0 license. The benefits would be mainly:

* Lightning-fast text searches with multiple words. 
* Other keywords such as song length could also be included. Or imagine searching for song by artist + title. "doriko romeo and cinderella"
* Language-specific analysis, for example splitting words based on language rules instead of just whitespace.
