### ISSUE TITLE
Ignore spaces in searchbar

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#671]
There are some artists that have/prefer a space between last and first name (Japanese). If you try to search them, the search will not find them because of the space.
Example: https://vocadb.net/Ar/84623

**Comment by dset0x** [comment]
I don't see any spaces in the Japanese name of that artist. What is it that you searched in the search bar?

**Comment by andreoda** [comment]
Please also read the comments. There was an issue with that.

**Comment by dset0x** [comment]
I see. For clarity, the artist's name in vocadb used to be "山田 むらう" and searching for "山田むらう" wouldn't yield a result.

**Comment by riipah** [comment]
Title makes it sound like you want to type a name with space (for example 山田 むらう), and have it converted to name without space, which already works just fine, but actually it's the reverse. The complication is because the system has no way of knowing how to separate that "山田むらう" without Japanese language rules. The way VocaDB search works is that it splits the names separated by whitespace. If there is no whitespace, it cannot be split, so it will be searched as is.

Perhaps there is a library that would do that, but it still won't be 100% accurate. I know libraries like Lucene do this for text analysis.

Another solution would be to always include a variant of the name without spaces, so editor would enter "山田 むらう" and it would also be saved without space.

For now, as a workaround, I would recommend always entering the name without spaces, or at least including it as an alias, that way the system will find it when searching with or without spaces.

**Comment by andreoda** [comment]
Sorry for the confusion and thanks a lot for the feedback!
