### ISSUE TITLE
Associating an artist with multiple base voice banks

### ISSUE THREAD

**Issue by hikaruso** [VocaDB/vocadb#706]
"Synthesizer V Kotonoha Akane & Aoi" is a single voice bank with two base voicebanks: [VOICEROID Kotonoha Akane](https://vocadb.net/Ar/40988) and [VOICEROID Kotonoha Aoi](https://vocadb.net/Ar/40989). 

Since the current system allows only one base voicebank to be set, it has been tentatively split into the following two artist entries to avoid this problem.
* [Kotonoha Akane (Synthesizer V)](https://vocadb.net/Ar/81912)
* [Kotonoha Aoi (Synthesizer V)](https://vocadb.net/Ar/85936)

This voice bank can be Akane or Aoi, depending on the intention of the producer of the song. In some cases, the intention may be unclear or may not dare to be specified.

In this case, according to the current operation rules, both "Kotonoha Akane (Synthesizer V)" and "Kotonoha Aoi (Synthesizer V)" must be registered, even if the song is sung by one singer, which is unnatural.

Therefore, I think it would be ideal to create a new artist entry named "Kotonoha Akane & Aoi (Synthesizer V)" and set "VOICEROID Kotonoha Akane" and "VOICEROID Kotonoha Aoi" as the base voicebank.

Ideal state
>Kotonoha Akane (Voiceroid)
>Kotonoha Aoi (Voiceroid)
>└ Kotonoha Akane & Aoi (Synthesizer V)
>　 └ Kotonoha Akane (Synthesizer V)
>　 └ Kotonoha Aoi (Synthesizer V)

For this reason, I would like to propose a change to the system as shown in the title.

**Comment by riipah** [comment]
Currently some artist roles such as illustrator and voice provider are inherited from base voicebank. Most likely these should be the same for all base voicebank, so there's probably no conflict, but there needs to be some way to resolve that.

This would require changing the association from one-to-many to many-to-many, which will of course have an effect on performance and complexity.

If it's just this one case, I would recommend not doing this, because of performance and added complexity. But if there will be multiple more similar cases, then it might be worth it.

**Comment by hikaru-soeda** [comment]
I think cases like "Synthesizer V Kotonoha Akane & Aoi" are probably very rare.

If no changes are made to the system, there are 3 options for action to be taken
- a) As it is now. (Set up two artist entries, even if only one vocalist sings)
- b) Accept the problem of the base voicebank and revert back to before splitting the entry. (Before splitting the entry, "VOICEROID Kotonoha Akane" was set as the base voicebank and "VOICEROID Kotonoha Aoi" was set as the external link)
- c) Accept the problem of the base voicebank and create a new entry named "Kotonoha Akane & Aoi (Synthesizer V)".

I think c) is better, but I would like to hear your opinion.

**Comment by riipah** [comment]
I see external link as a more than acceptable workaround for a rare situation like this, but it's ok to keep this issue here if happen to have more similar cases in the future.

I think this is the worst place to discuss which is the right option, because there is less people here. Better discuss it on Discord, like andrea suggested.
