### ISSUE TITLE
"Import from YouTube or NicoNico" does not support new NND Mylist URL

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#708]
**Website**
VocaDB

**Describe the bug**
"[Import from YouTube or NicoNico](https://vocadb.net/SongList/Import)" does not support the new(?) Niconico Douga Mylist URL format. Instead, the underlying API (`https://vocadb.net/api/songLists/import`) returns `400 Bad Request`. The API can handle the URL fine if it is modified to the old format.
- Old: `https://www.nicovideo.jp/mylist/2675058`
- New: `https://www.nicovideo.jp/user/2523470/mylist/2675058`

**Comment by ycanardeau** [comment]
We need to update [ArtistExternalUrlParser](https://github.com/VocaDB/vocadb/blob/master/VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs), [WebLinkMatcher](https://github.com/VocaDB/vocadb/blob/e96b44e6c7970e5300e6780aad2d39cf91a65509/VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts#L67) as well, but it's impossible now. For WebLinkMatcher, we need to use regex instead of `indexOf`.

**Comment by riipah** [comment]
As an implementation details, maybe add matchMode parameter to WebLinkMatcher, so preserve the old (possibly faster) match mode in addition to regex. Actually prefix matcher could be added as well, it should be even faster.

**Comment by ycanardeau** [comment]
Fixed and deployed, thanks for reporting!

**Comment by szc126** [comment]
Hm, the URL works now, but the My List returned seems to be truncated to 30 items :s

**Comment by szc126** [comment]
It also appears to be pulling items from a user's other MyLists, as well as another source (???).
Such as `https://www.nicovideo.jp/user/756019/mylist/19970952`. Some of the videos are from https://www.nicovideo.jp/user/756019/mylist/19970952 and https://www.nicovideo.jp/user/756019/mylist/19890378.

**Comment by ycanardeau** [comment]
> Hm, the URL works now, but the My List returned seems to be truncated to 30 items :s

@szc126 It's because [the underlying API](https://github.com/VocaDB/vocadb/blob/4fa48be2f8e0b05ea6f81e5f8ce629a489249de1/VocaDbModel/Service/SongImport/NicoNicoMyListParser.cs#L45) parses [the RSS Feed](https://www.nicovideo.jp/user/756019/mylist/8264497?rss=2.0), which contains only 30 items. We need to write a new parser for Niconico Douga Mylist.

**Comment by szc126** [comment]
@ycanardeau I should have noted that "converting" a MyList URL to the old format (= removing `user/XXX`) is a functional workaround.
