### ISSUE TITLE
A "root event" filter for the event search page

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#720]
Similar to the "root voicebank" filter for the artist search page.
Could be useful for finding specific parent events only, for example character anniversary events.

Personal issue: If I search for character anniversaries, the site shows me all, which are a lot. I would like to see only parent events for character anniversaries.

**Comment by riipah** [comment]
When you say "root event", do you mean event series? It's different case from root voicebanks, because events and event series are two different objects with slightly different properties. But I guess there could be some sort of search page for event series, just not sure if it can be same page with events.

**Comment by riipah** [comment]
Oh I guess you mean event series filter for event search page? Like the tag category filter for tags?

**Comment by andreoda** [comment]
![grafik](https://user-images.githubusercontent.com/52045122/103888451-0d8cdb80-50e5-11eb-9c3c-e31aff4bc12d.png)
Currently seeing so many events in character anniversary but I only want to see the root/parent events for example only Meiko's base birthday event (series), not the children of it, like 2012, 2013 etc.

**Comment by riipah** [comment]
Okay yeah, that's what I understood first. So they want to list event series instead of events. Sounds like in this case, adding search field for event series does not solve the use case, we would need another search page for event series, or somehow have both series and events in the same list. Perhaps some sort of mode check (show events vs. series).
