### ISSUE TITLE
Switching between YouTube/NicoNico when in playlist mode

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#754]
A problem that was already described in https://github.com/VocaDB/community/issues/32 but needed another issue entry.

**Context:**
When I am using the playlist function with activated autoplay, the videos do not skip automatically to the next when I have the tab minimized or I am simply not on the tab where the playlist plays. This happens only with NND videos. (This probably needs another issue entry because it is a bug)

**Solution:**
It would be nice to have a function (filter/button) that lets me choose if I want the player to priorize YouTube or NND etc.
It should also consider "Reprints" or "Other" media.

Regarding the solution:
There is already a way to priorize the media in the users settings, why is the playlist not affected by it?

![grafik](https://user-images.githubusercontent.com/52045122/106674003-d8c05700-65b2-11eb-874a-9a35ff4a9871.png)

**Comment by riipah** [comment]
The idea was that the playlist mode would attempt to reduce switching players, because it causes delays. So if you're playing a song that is only available on NicoNico, if the next song is available on NicoNico and YouTube, it would choose NicoNico, even if your preference is YouTube, to avoid switching the player.

Not being able to switch songs while in the background may be something that is out of our hands.
