### ISSUE TITLE
Advanced search filters not working

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#793]
From: https://vocadb.net/discussion/topics/372

Advanced search filters do not seem to work.

https://vocadb.net/Search?searchType=Song

**Comment by riipah** [comment]
Sounds like this is related to model binding changes in ASP.NET Core. Since it's a GET request, parameters are sent in the query string. The advanced search parameter is an array of structured type, seems to be sent as x-www-form-urlencoded (?). Since ASP.NET Core is more strict, it probably won't parse this by default. I'm unsure how to use structured arrays with GET requests in ASP.NET Core. 

Possible solutions:
* Custom model binder. 
* Alternative POST endpoint, which takes the parameters as JSON instead, in which case it won't be a problem (the default endpoint should still be GET though, because GET should be used for querying data). 
* Advanced search parameters could be serialized into some more simple format (it's mainly key-value pairs anyway).

**Comment by ycanardeau** [comment]
@riipah Thanks for your advice, but I fixed it by creating [a new class](https://github.com/VocaDB/vocadb/pull/800/files#diff-9580cb423c5614917c0aa13af110ae94b4b56ab70eed341229b644d0506bb1a1).

**Comment by riipah** [comment]
Yeah that was the "ASP.NET Core" solution I was referring to. Good thing there was a Stackoverflow article, and you found it. Thanks for fixing it!
