### ISSUE TITLE
A field to copy-paste the video description

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#912]
For song entries

**Is your feature request related to a problem? Please describe.**
- people forget to add information
- people can't find information (they don't look into the video description)
- video got deleted and info/video description is missing now

**Describe the solution you'd like**
A field meant to put the video's description in by copy-paste. From video sites like YouTube, NicoNicoDouga and bilibili.

**Describe alternatives you've considered**
The normal description field is not there to copy-paste the video description, since it is (in most times) written in first person.
The "artist's personal description" field is only meant for registered and verified artists/producer to put their own (first person) description in.

Maybe expand the usage for the "artist's personal description", so that it is allowed to copy-paste the video description but that is not possible since only verified artists and mods are allowed to use this.

**Additional context**
If a new field is created for this, maybe the system could automatically input the video description. If a video has two or three uploads or are on different sites (YT and NND) that would not work though.

**Comment by ycanardeau** [comment]
This is definitely useful for several reasons, this task needs some more planning.

@andreoda Could you please explain a little bit more, why you need a new field to copy and paste the video description, rather than to use the existing one? How about adding a new field to PVs instead of a song? By PVs, I mean the entries in the `Media` tab on the song edit page.

**Comment by andreoda** [comment]
That idea makes more sense than using the artist description (originally meant for the producer) or normal entry description (meant for info other than "copy-paste"). That way, the video description is connected to the belonging video/PV.
How would that look like? Maybe a tab that collapses once clicked on it under the PV? or maybe on top of the PV media on the right side (empty space besides the embedded media)?

**Comment by ycanardeau** [comment]
> That way, the video description is connected to the belonging video/PV.

That's exactly why I suggested adding a new field to PVs rather than a song. If we added a field to a song, then we could have only one description per song. There might be some cases where the video description differs from service to service (e.g. YouTube and NND).

> How would that look like?

Actually, we wouldn't need a field on the edit page, if the system automatically inputs the video description, in which case you can't edit it manually though. By a field, I mean not only a text field, but also a database column. Let's say you added two PVs (YouTube and NND) and then clicked on "Save changes". The system makes API requests to YouTube and NND, and then saves the two (possibly) different video descriptions into the database. When you visit the song details page, one of the descriptions appears. Perhaps we could switch between descriptions by clicking a tab, just like the translated description.

**Comment by andreoda** [comment]
The idea is super good but what would happen if A the description was changed by the uploader or B the PV got deleted. It is a bit tricky.

**Comment by ycanardeau** [comment]
>  the description was changed by the uploader

We have two options:

1. update it manually (similar to the `Refresh PV metadata` button)
2. update it automatically by regularly making API requests

I think option 1 is enough.

> the PV got deleted

In this case, we don't need to do anything. The description is already stored in our database.
