### ISSUE TITLE
More filters for search and edit mode: languages/lyrics+

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#940]
Currently, the search can be used to find following languages in songs:
- any language
- Japanese
- Chinese
- English
- Other

These are based on the lyrics tab in song entries. Only if they were added.
Additionally, tags can used to find specific languages but only if that language is uncommon for specific voice synthesizer. Example: We tag songs with the "English" tag if Hatsune Miku V2 was used (That voicebank doesn't have an English option naturally).

A more obvious/easy way for people would be to have a section in the song and album edit mode to set the language(s) that were sung in the song. It should be possible to set multiple languages for a song. (For albums: Should be automatically added/calculated by the system based on the songs/tracks inside of it)
Also, the options should be at least as wide as the lyrics tab provides, not only Japanese, Chinese and English.

The search should also have a section based on the language of the song, so that people can easily find specific songs based on languages.

Based on this conversation/issue:
![grafik](https://user-images.githubusercontent.com/52045122/129357449-520e26b6-552c-46b0-891c-9b52b47d0d86.png)

**Comment by Shiroizu** [comment]
It sounds like a lot of future edit work if a new data field were to be created for the song entries.

How would the existing 300k song entries be handled? Also, would this be a required field for the entry to be considered finished in the future? Would the filter be useful if it only included a small portion of the songs? If searching "Japanese" songs returned only 10% of them it would feel a bit useless (even for this 10%, a total of ~25k songs would need to be edited).

Having the language as a "primitive" data type (instead of tags) would be intuitive, but honestly the benefits are a bit too small considering how much effort this would require.

Also, it's not generally too efficient to have the data duplicated somewhere else (song entries in this case). For example, songs by Miku (or any other JP-only voicebank) can be considered Japanese, unless the English or some other language tag is present.

I think this approach could maybe be used to create a new advanced song search filter.
